### ISSUE TITLE
Question: inverse function to `ede-php-autoload-find-class-def-file`?

### ISSUE THREAD

**Issue by trashofmasters** [stevenremot/ede-php-autoload#7]
Hi Steven,

I'd like to write a skeleton to generate the following file template, where `<namespace_name>` is the path to the file converted to a fully qualified name via PSR-4, minus the class name, which  will go into `<class_name>`.

```php
<?php

namespace <namespace_name>;

class <class_name>
{
}
```

Is there already a function or a method that I can call from outside your package to obtain this information?

Thanks.

**Comment by stevenremot** [comment]
Hi Andrea,

I didn't implement this kind of function, but that's an excellent idea. I'm not sure it would be easy for PSR-0 norm as it accepts underscores and backslashes as namespace separators, but for PSR-4 it should be feasible.

**Comment by stevenremot** [comment]
Hi @trashofmasters ,

I could implement the classname guessing for PSR-4 namespaces. It is pushed on branch [#7-create-class-name-from-file-name](https://github.com/stevenremot/ede-php-autoload/tree/%237-create-class-name-from-file-name).

For PSR-0 I can't get a correct answer every time, because a file name separator can mean either "\" or "_". When the namespace autoloading configuration has a sub-namespace in it, like this:

```json
{
  "autoload": {
    "psr-0": {
      "MyNs_MySubNs_": "..."
    }
  }
}
```

Then I can detect the underscore and replace all directory separators by underscores when guessing the class name, but even this is not guaranteed to be correct if one mixes underscores and antislashes in the class name.

If I understand correctly you would use it only with PSR-4 namespaces for now. If so I'm in favor of not supporting class guessing on PSR-0 unless someone needs it, and then we may think about a good enough approach to cover most use cases. 

What are your thoughts on it ?

**Comment by trashofmasters** [comment]
Thanks for the update, I'm eager to test this new functionality.

As far as generating the class and namespace name for a template is concerned I suppose that the problems that you have mentioned are only minor.

> If so I'm in favor of not supporting class guessing on PSR-0 unless someone needs it, and then we may think about a good enough approach to cover most use cases.

I'm with you on this one.

**Comment by stevenremot** [comment]
Thanks for the answer!

I have merged the branch to master, so now I close this issue.
