### ISSUE TITLE
Feature request: Local variable return type hints for semantic

### ISSUE THREAD

**Issue by periklis** [stevenremot/ede-php-autoload#8]
Hi,
excellent work so far for navigating in a composer based application on the tracks of semanticdb. Since this works on top of the parser, i would like to propose for the typical php-project return type declaration method, which is mainly used in other IDEs. However, since PHP 7 adoption, which includes return type declarations officialy, will take its time in the frameworks and application out there, why not adopt the following common used method:

``` php
/** @var $myRepository Bundle\Package\ParentDir\SubDir\MyRepository */
$myRepository = $container->getMyRepository();
```

Is it possible to parser the above with your wisent-php package? It would a killer feature in my humble opinion, for navigation through and completion of larger codebases without php-lang-based return-type declarations. This kind of return type hint will stay a long time with us, i think. What's your opinion?

**Comment by stevenremot** [comment]
Hi @periklis,

Sorry for the late reply, I was in vacation these last two weeks.

I totally agree parsing these kind of constructions would be really cool, and it was in my plans when I was actively working on my CEDET fork. As you should have guessed I stopped working on this fork. @jorissteyn is extracting the wisent stuffs from EDEP, and when it is done I would rather contribute to its project rather than keep coding on my fork and duplicating features! 

I think this issue should be opened on the upcoming @jorissteyn 's wisent-php project instead of this one, so I propose to leave it open on this project as a reminder, and to close it and reopen it in the right project when it is possible.

Are you okay with it?

**Comment by periklis** [comment]
Totally fine with it, i'll close this thread when @jorissteyn makes the wisent-php parser public.

**Comment by stevenremot** [comment]
Hey @periklis! I would like to clean a bit this repository. Do you mind if I close this issue, now that the wisent-php parser is released?

**Comment by periklis** [comment]
@stevenremot No problem, i am just curious which wisent-php-parser release you mean.

**Comment by stevenremot** [comment]
Thanks! I wasn't very clear, I was talking about jorissteyn/semantic-php. So nothing new, I'm just cleaning this repo a bit ;-)
